root: true

parser: 'babel-eslint'

extends:
  - eslint:recommended

env:
  node: true

parserOptions:
  ecmaVersion: 7

# List of available rules - ESLint http://eslint.org/docs/rules/
rules:
  no-console: "off"
  no-constant-condition: "off"
