version: "3.9"
services:
  make:
    build: .
    image: knavi:latest
    volumes:
      - type: bind
        source: ./
        target: /work
    working_dir: /work
    entrypoint: ["./entrypoint.bash"]
