name: dry-build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  dry-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker compose run make zip
