name: dry-build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  dry-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: |
          docker buildx build \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            --load \
            -t knavi:latest \
            .
      - name: Build
        run: docker compose run make zip
