name: dry-build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  dry-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run zip
