name: release

on:
  push:
    tags: ["*"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: docker compose build --cache-from type=gha --cache-to type=gha,mode=max
      - name: Build
        run: docker compose run make zip
      - name: Release
        run: gh release create ${{ github.ref }} knavi-${{ github.ref_name }}.zip --notes-file changelog/${{ github.ref_name }}.md
        env:
          GH_TOKEN: ${{ github.token }}
