name: release

on:
  push:
    tags: ["*"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker compose run make zip
      - name: Release
        run: gh release create ${{ github.ref }} knavi-${{ github.ref_name }}.zip --notes-file changelog/${{ github.ref_name }}.md
        env:
          GH_TOKEN: ${{ github.token }}
